// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Scrobble struct {
	ID          int64
	ListenedAt  time.Time
	Username    string
	UserUuid    string
	CoverArtID  string
	DurationMs  int32
	ArtistName  string
	TrackName   string
	ReleaseName string
}
