// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"time"
)

const createScrobble = `-- name: CreateScrobble :one
INSERT INTO scrobbles (
    listened_at,
    username,
    user_uuid,
    cover_art_id,
    duration_ms,
    artist_name,
    track_name,
    release_name
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8
         )
RETURNING id, listened_at, username, user_uuid, cover_art_id, duration_ms, artist_name, track_name, release_name
`

type CreateScrobbleParams struct {
	ListenedAt  time.Time
	Username    string
	UserUuid    string
	CoverArtID  string
	DurationMs  int32
	ArtistName  string
	TrackName   string
	ReleaseName string
}

func (q *Queries) CreateScrobble(ctx context.Context, arg CreateScrobbleParams) (Scrobble, error) {
	row := q.db.QueryRowContext(ctx, createScrobble,
		arg.ListenedAt,
		arg.Username,
		arg.UserUuid,
		arg.CoverArtID,
		arg.DurationMs,
		arg.ArtistName,
		arg.TrackName,
		arg.ReleaseName,
	)
	var i Scrobble
	err := row.Scan(
		&i.ID,
		&i.ListenedAt,
		&i.Username,
		&i.UserUuid,
		&i.CoverArtID,
		&i.DurationMs,
		&i.ArtistName,
		&i.TrackName,
		&i.ReleaseName,
	)
	return i, err
}

const getAllScrobbles = `-- name: GetAllScrobbles :many
SELECT id, listened_at, username, user_uuid, cover_art_id, duration_ms, artist_name, track_name, release_name
FROM scrobbles
ORDER BY listened_at DESC
`

func (q *Queries) GetAllScrobbles(ctx context.Context) ([]Scrobble, error) {
	rows, err := q.db.QueryContext(ctx, getAllScrobbles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scrobble
	for rows.Next() {
		var i Scrobble
		if err := rows.Scan(
			&i.ID,
			&i.ListenedAt,
			&i.Username,
			&i.UserUuid,
			&i.CoverArtID,
			&i.DurationMs,
			&i.ArtistName,
			&i.TrackName,
			&i.ReleaseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
